# Generated by Django 5.2 on 2025-04-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='timeOfDay',
        ),
    ]
