# Generated by Django 5.2 on 2025-04-20 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_scheduler', '0002_remove_section_timeofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='timeOfDay',
            field=models.TimeField(default=datetime.time(0, 0), help_text='This field expects time in 24-hour format (HH:MM).'),
        ),
    ]
